version: '3'
services:
  mysql-db:
    image: mysql:latest
    container_name: mysql_camunda
    ports:
    - '3306:3306'
    volumes:
      - /home/dmorales/volumenesDocker/mysql_bpm:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: camunda_db

  camunda:
    image: camunda/camunda-bpm-platform:run-latest
    container_name: camunda_bpm
    ports:
    - '8080:8080'
    environment:
      DB_DRIVER: com.mysql.jdbc.Driver
      DB_URL: jdbc:mysql://mysql-db:3306/camunda_db?autoReconnect=true
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - 'mysql-db'

  frontend:
    image: h4ndshake/proyecto-final:app-react_latest
    container_name: frontend
    network_mode: "host"   
    depends_on:
      - 'camunda' 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql-db
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8082:80
    depends_on:
      - 'mysql-db'

  selenium:
    image: selenium/standalone-firefox
    container_name: selenium
    network_mode: "host"
